[settings]
gpg_verify = false

[tools]
"aqua:astral-sh/ruff" = "latest"
"aqua:astral-sh/uv" = "latest"
"aqua:charmbracelet/crush" = "latest"
"aqua:dandavison/delta" = "latest"
"aqua:hashicorp/vault" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:neovim/neovim" = "latest"
"aqua:pnpm/pnpm" = "latest"
"aqua:tree-sitter/tree-sitter" = "latest"
"cargo:codebook-lsp" = "latest"
go = "latest"
node = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@mdx-js/language-server" = "latest"
"npm:npmrc" = "latest"
"npm:vibe-rules" = "latest"
"pipx:basedpyright" = "latest"
python = "latest"
rust = "latest"
usage = "latest"
