[settings]
gpg_verify = false

# tombi: format.rules.table-keys-order = "ascending"
[tools]
"aqua:Automattic/harper/harper-ls" = "latest"
"aqua:JohnnyMorganz/StyLua" = "latest"
"aqua:LuaLS/lua-language-server" = "latest"
"aqua:artempyanykh/marksman" = "latest"
"aqua:astral-sh/ruff" = "latest"
"aqua:astral-sh/uv" = "latest"
"aqua:biomejs/biome" = "latest"
"aqua:charmbracelet/crush" = "latest"
"aqua:dandavison/delta" = "latest"
"aqua:google/yamlfmt" = "latest"
"aqua:hadolint/hadolint" = "latest"
"aqua:hashicorp/terraform-ls" = "latest"
"aqua:hashicorp/vault" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:koalaman/shellcheck" = "latest"
"aqua:mvdan/sh" = "latest"
"aqua:neovim/neovim" = "latest"
"aqua:pnpm/pnpm" = "latest"
"aqua:rust-lang/rust-analyzer" = "latest"
"aqua:tombi-toml/tombi" = "latest"
"aqua:tree-sitter/tree-sitter" = "latest"
"cargo:codebook-lsp" = "latest"
"cargo:selene" = "latest"
go = "1"
"go:github.com/mattn/efm-langserver" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
node = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@mdx-js/language-server" = "latest"
"npm:@microsoft/compose-language-service" = "latest"
"npm:@qwen-code/qwen-code" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:gh-actions-language-server" = "latest"
"npm:markdownlint-cli" = "latest"
"npm:npmrc" = "latest"
"npm:prettier" = "latest"
"npm:vibe-rules" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
"pipx:basedpyright" = "latest"
"pipx:isort" = "latest"
"pipx:jedi-language-server" = "latest"
"pipx:yamllint" = "latest"
python = "latest"
rust = "latest"
usage = "latest"
