[settings]
gpg_verify = false

# tombi: format.rules.table-keys-order = "ascending"
[tools]
"aqua:Automattic/harper/harper-ls" = "latest"
"aqua:JohnnyMorganz/StyLua" = "latest"
"aqua:LuaLS/lua-language-server" = "latest"
"aqua:artempyanykh/marksman" = "latest"
"aqua:astral-sh/ruff" = "latest"
"aqua:astral-sh/uv" = "latest"
"aqua:biomejs/biome" = "latest"
"aqua:charmbracelet/crush" = "latest"
"aqua:dandavison/delta" = "latest"
"aqua:google/yamlfmt" = "latest"
"aqua:hadolint/hadolint" = "latest"
"aqua:hashicorp/terraform-ls" = "latest"
"aqua:hashicorp/vault" = "latest"
"aqua:jdx/usage" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:koalaman/shellcheck" = "latest"
"aqua:mvdan/sh" = "latest"
"aqua:neovim/neovim" = "latest"
"aqua:pnpm/pnpm" = "latest"
"aqua:rust-lang/rust-analyzer" = "latest"
"aqua:tombi-toml/tombi" = "latest"
"aqua:tree-sitter/tree-sitter" = "latest"
"cargo:selene" = "latest"
claude = { version = "latest", bin = "claude", platforms = """
[linux-arm64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{{ version }}/linux-arm64/claude"

[linux-x64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{{ version }}/linux-x64/claude"

[macos-arm64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{{ version }}/darwin-arm64/claude"

[macos-x64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{{ version }}/darwin-x64/claude"

[windows-x64]
bin = "claude.exe"
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{{ version }}/win32-x64/claude.exe"
""", version_list_url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/latest" }
"github:skanehira/version-lsp" = "latest"
go = "1.25.6"
"go:github.com/mattn/efm-langserver" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
node = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@mdx-js/language-server" = "latest"
"npm:@microsoft/compose-language-service" = "latest"
"npm:@qwen-code/qwen-code" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:gh-actions-language-server" = "latest"
"npm:markdownlint-cli" = "latest"
"npm:npmrc" = "latest"
"npm:prettier" = "latest"
"npm:vibe-rules" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
"pipx:basedpyright" = "latest"
"pipx:isort" = "latest"
"pipx:jedi-language-server" = "latest"
"pipx:mistral-vibe" = "latest"
"pipx:yamllint" = "latest"
python = "latest"
rust = "latest"
